# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('muscule_group', models.CharField(choices=[('ch', 'Chest'), ('ar', 'Arms'), ('le', 'Legs'), ('ab', 'Abs')], max_length=2)),
                ('order', models.IntegerField(default=0)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Workout')),
            ],
        ),
    ]
