# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20171002_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('rep_number', models.IntegerField(default=1)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Exercise'),
        ),
    ]
