# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_auto_20171009_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('db', 'Dumbbell'), ('bb', 'Barbell'), ('bw', 'Body Weight'), ('rb', 'Resistance Bands'), ('ma', 'Machine')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
