# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_auto_20171009_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='counter.Exercise'),
        ),
    ]
