# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0008_auto_20171009_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='set_number',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='counter.Workout'),
        ),
    ]
