# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0009_auto_20171009_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rep_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='set_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
