# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_auto_20171010_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='rep_number',
            new_name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='set_number',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default=1),
        ),
    ]
