# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0013_auto_20171016_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='counter.Workout'),
        ),
    ]
