# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0014_auto_20171016_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='order',
        ),
    ]
