# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0015_remove_exercise_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workouts',
            field=models.ManyToManyField(to='counter.Workout'),
        ),
    ]
