# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0016_exercise_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workouts',
        ),
    ]
