# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0017_remove_exercise_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workouts',
            field=models.ManyToManyField(to='counter.Workout'),
        ),
    ]
